upstream qreport-backend {
  server unix:/run/${instance_name}/${instance_name}.sock;
}

server {
  listen 80;
  listen [::]:80;
  server_name ${server_name};

  location /admin {
    auth_basic "Admin";
    auth_basic_user_file /usr/local/etc/wsgi/${instance_name}/.htpasswd;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://qreport-backend;
  }

  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://qreport-backend;
  }
}
